name = "groupmyclass"
main = "src/index.js"
compatibility_date = "2026-09-02"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "groupmyclass"
database_id = "ffb52212-2ce5-4335-a9d3-6cf70e43a732"
